services:
  attendance-bot:
    build: .
    container_name: attendance-bot
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
